In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.1910e-09, grad_fn=<MeanBackward0>)

In [4]:
class Mylinear(nn.Module):

    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = Mylinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.7065, -0.5121, -1.6518],
        [ 2.3792, -1.2776,  0.1222],
        [ 0.1096,  0.8646, -0.0796],
        [ 1.7252,  0.4703,  2.0613],
        [ 1.8820, -0.5622,  1.0342]], requires_grad=True)

In [5]:
linear(torch.rand(2, 5))

tensor([[0.9154, 0.5221, 2.5321],
        [2.0139, 0.8362, 3.9176]])

In [8]:
net = nn.Sequential(Mylinear(64,8), Mylinear(8,1))
net(torch.randn(2, 64))

tensor([[11.0008],
        [23.1612]])